build: off

install:
- cmd: c:\python39\python.exe -m pip install --upgrade pip
- cmd: c:\python39\python.exe -m pip install tox

test_script:
- cmd: set PATH=c:\python39;c:\python39\Scripts;%PATH%
- tox -e example
