# Results at https://ci.appveyor.com/project/tmarktaylor/phmdoctest
build: off

install:
# It is advisable to install in a virtual environment.
# Use the pre-installed python image to create the virtual environment.
# https://packaging.python.org/guides/installing-using-pip-and-virtual-environments
# https://www.appveyor.com/docs/windows-images-software#python
- cmd: py -m venv env
- cmd: .\env\Scripts\activate
- cmd: where python
- cmd: python -m pip install --upgrade pip
- cmd: python -m pip --version
- cmd: python -m pip install --no-deps "."
- cmd: python -m pip install -r requirements.txt
- cmd: python -m pip install "pytest>=6"

test_script:
# Create directory "tmp" for the generated pytest file.  Use Windows backslash.
# Run phmdoctest to generate the test file and print the report.
# Run the phmdoctest test suite including the generated pytest file in "tmp".
- cmd: mkdir tests\tmp
- cmd: phmdoctest project.md --report --outfile tests/tmp/test_project.py
- cmd: pytest --doctest-modules -vv tests
